# Generated by Django 4.2.1 on 2023-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_leagueplayers_qualifiedscore_leagueplayers_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='highestEvent',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoreAverage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoreMinimum',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoreRange',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoreThreshold',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='totalEventScore',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='adjustedScore',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='attendanceBoost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='confidenceRating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='events',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='eventsTotalScore',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='highScore',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='lastEventDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='qualifiedScore',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='score',
            field=models.FloatField(default=1500, null=True),
        ),
        migrations.AlterField(
            model_name='leagueplayers',
            name='tops',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
