# Generated by Django 4.2.1 on 2023-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_league_highestevent_alter_league_scoreaverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueplayers',
            name='lastEventDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
